# Generated by Django 6.0 on 2025-12-24 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('college_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Jina la Chuo')),
                ('is_salafi', models.BooleanField(default=False, verbose_name='Je, ni Chuo cha Kisalafi?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Chuo',
                'verbose_name_plural': 'Vyuo',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExternalIslamicFacility',
            fields=[
                ('facility_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Jina la Kituo/Eneo')),
                ('location', models.CharField(max_length=500, verbose_name='Mahali/Anwani')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('college', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vituo.college', verbose_name='Chuo Kinachohusika')),
            ],
            options={
                'verbose_name': 'Kituo cha Kiislamu Nje ya Chuo',
                'verbose_name_plural': 'Vituo vya Kiislamu Nje ya Vyuo',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Muswallah',
            fields=[
                ('muswallah_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Jina la Msikiti/Muswallah')),
                ('is_salafi', models.BooleanField(default=False, verbose_name='Je, ni ya Kisalafi?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miswallah', to='vituo.college', verbose_name='Chuo')),
            ],
            options={
                'verbose_name': 'Muswallah/Msikiti',
                'verbose_name_plural': 'Miswallah/Misikiti',
                'ordering': ['name'],
            },
        ),
    ]
